### ISSUE TITLE
Delete Response has false Content-Type

### ISSUE THREAD

**Issue by benno208** [ethanresnick/json-api#25]
I'm doing some testing with supertest:

    request(app)
            .delete '/some/' + someId.toString()
            .set headers
            .expect 'Content-Type', headers['Accept']
            .expect 204
            .end done

    headers =
            'Content-Type' : 'application/vnd.api+json; charset=utf-8'
            'Accept' : 'application/vnd.api+json; charset=utf-8; supported-ext=bulk'

I get the following error:

    Error: expected "Content-Type" of "application/vnd.api+json; charset=utf-8; supported-ext=bulk", got "application/vnd.api+json; supported-ext="bulk""

GET, POST and PATCH work very well

**Comment by ethanresnick** [comment]
Hi @benno208, 

Thanks for reporting this! I just pushed a new version of the library that shouldn't have this problem; can you check?

Here's how it should behave now. First, the server should no longer send, and clients no longer need to indicate that they'll `Accept`, the `supported-ext` parameter. This is because extensions have now been marked [as experimental](http://jsonapi.org/extensions/) and, in fact, the whole extension negotiation system [may well change](https://github.com/json-api/json-api/pull/650). So, until the extension system is more solid, I've chosen not to support the `ext` and `supported-ext` at all.

As for the `charset` parameter: if a client includes it in the `Accept` header, JSON API [requires](http://jsonapi.org/format/#content-negotiation-servers ) that the server respond with a `406 Not Acceptable`. The idea is that, by requiring an explicit error, JSON API can add new parameters in the future (like `ext`) to the base spec, and clients can detect server support for those new parameters by seeing whether they get a 406.

The story with `charset` in `Content-Type` is different, though. First, express adds `charset` automatically, so there's little I can do about that. This is bad behavior on express's part, since JSON API's media type doesn't define a `charset` parameter, but it's not technically a violation of the [media type spec](https://www.ietf.org/rfc/rfc2045.txt). Nevertheless, if a client encounters `charset` in `Content-Type`, it MUST simply ignore it. This comes from [JSON API](http://jsonapi.org/format/#content-negotiation-clients) but also from the media type spec, which says that "MIME implementations must ignore any parameters whose names they do not recognize".

So, in the end, here's what this adds up to:

1. Your test client's `Accept` header should be simply `application/vnd.api+json`, since `supported-ext` is gone and including `charset` will trigger the JSON-API-mandated 406.

2. Your client's `Content-Type` header should simply be `application/vnd.api+json` as well, as mandated [here](http://jsonapi.org/format/#content-negotiation-clients). 

3. Then, your expect clause should be that the returned `Content-Type` will be `application/vnd.api+json; charset=utf8`, _even though this doesn't match the `Accept` header_. This is a bit annoying—and it's a consequence of express's insistence on adding the `charset` parameter automatically, which I'd like to figure out some way to disable. But it's perfectly valid under HTTP, which says that using negotiation is optional ("If...none of the available representations for the response have a media type that is listed as acceptable, the origin server can... disregard the header field by treating the response as if it is not subject to content negotiation"). Moreover, it's consistent with JSON API's restrictions as well.

**Comment by benno208** [comment]
First thing after updating to 2.3.0 is:

    Cannot find module 'babel-core/polyfill'

**Comment by ethanresnick** [comment]
Weird.... I just did a fresh install and things appear to be running fine. Can you give me the stack trace for that error?

**Comment by benno208** [comment]
I did a complete install. Now everything seems to be fine. When I do a POST I get 

    expected "Content-Type" of "application/vnd.api+json; charset=utf-8", got "application/json; charset=utf-8"

and on PATCH:

    Error: expected "Content-Type" of "application/vnd.api+json; charset=utf-8", got "application/vnd.api+json"

**Comment by ethanresnick** [comment]
What's the Accept header you're sending? For some reason, it's thinking that generic JSON should be used rather than the JSON API media type.

**Comment by benno208** [comment]
I'm sending the following headers:

    headers =
      'Content-Type' : 'application/vnd.api+json'
      'Accept' : 'application/vnd.api+json'

And I'm testing for:

    response_headers =
       'Content-Type' : 'application/vnd.api+json; charset=utf-8'

**Comment by benno208** [comment]
Damn, I clicked the false button...

**Comment by ethanresnick** [comment]
Very weird...what you posted earlier should have worked (and was working for me). However, I've just pushed a new version of the library that removes the automatically-appended charset parameter all together. So now you should be able to send a request with:

```
Content-Type: application/vnd.api+json
Accept : application/vnd.api+json
```

And get back

```
Content-Type: application/vnd.api+json
```

There's [a test](https://github.com/ethanresnick/json-api/blob/master/test/integration/content-negotiation/index.js#L29) for this behavior and, on my machine at least, it's passing. Let me know if you're still experiencing problems after upgrading to the latest version :)

**Comment by benno208** [comment]
Now, everything works like expected. Thanks!

**Comment by ethanresnick** [comment]
Awesome!
